"""Initial migration.

Revision ID: 94627af45711
Revises:
Create Date: 2025-07-21 20:32:14.566763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94627af45711'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vatable', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_items_sale_id'), ['sale_id'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('points_earned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('split_payment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_payment_method'), ['payment_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_receipt_number'), ['receipt_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_sale_date'), ['sale_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_sales_location_id', 'locations', ['location_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_location_id', 'locations', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_location_id', type_='foreignkey')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_location_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_user_id'))
        batch_op.drop_index(batch_op.f('ix_sales_sale_date'))
        batch_op.drop_index(batch_op.f('ix_sales_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_sales_payment_method'))
        batch_op.drop_index(batch_op.f('ix_sales_customer_id'))
        batch_op.drop_column('location_id')
        batch_op.drop_column('split_payment')
        batch_op.drop_column('points_earned')
        batch_op.drop_column('channel')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_items_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_items_product_id'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))
        batch_op.drop_column('vatable')

    # ### end Alembic commands ###
