"""empty message

Revision ID: e9_add_item_and_category_tables
Revises:
Create Date: 2025-10-19 11:18:20.265470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9_add_item_and_category_tables'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_purchase_order_items_product_id_products', type_='foreignkey')
        batch_op.create_foreign_key('fk_purchase_order_items_item_id_items', 'items', ['item_id'], ['id'])
        batch_op.drop_column('product_id')

    with op.batch_alter_table('supplier_quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_supplier_quotation_items_product_id_products', type_='foreignkey')
        batch_op.create_foreign_key('fk_supplier_quotation_items_item_id_items', 'items', ['item_id'], ['id'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_supplier_quotation_items_item_id_items', type_='foreignkey')
        batch_op.create_foreign_key('fk_supplier_quotation_items_product_id_products', 'products', ['product_id'], ['id'])
        batch_op.drop_column('item_id')

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_purchase_order_items_item_id_items', type_='foreignkey')
        batch_op.create_foreign_key('fk_purchase_order_items_product_id_products', 'products', ['product_id'], ['id'])
        batch_op.drop_column('item_id')

    op.drop_table('items')
    op.drop_table('categories')
    # ### end Alembic commands ###
